version: '3.8'

services:
  architect-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "51773:51773"
    container_name: architect-portfolio
    restart: unless-stopped
    depends_on:
      - blog-api

  blog-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: paraflux-blog-api
    restart: unless-stopped
